//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActCreator.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActsHistory
    {
        public int IdHistory { get; set; }
        public string FullInfo { get; set; }
        public byte[] Act { get; set; }
    }
}
