//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActCreator.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActCreatorAppDBEntities : DbContext
    {
        public ActCreatorAppDBEntities()
            : base("name=ActCreatorAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActsHistory> ActsHistory { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<TempColumnWorks> TempColumnWorks { get; set; }
    }
}
