//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActCreator.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempColumnWorks
    {
        public int IdWork { get; set; }
        public string WorkName { get; set; }
        public double WorkPrice { get; set; }
    }
}
